### ISSUE TITLE
Automated pypi packaging

### ISSUE THREAD

**Issue by cumason123** [cloudevents/sdk-python#86]
## Expected Behavior
Merge v1.0.0-stable branch into master updates pypi

## Actual Behavior
Must run release.sh with proper permissions. 

We should setup a github action using:
https://github.com/pypa/gh-action-pypi-publish

An approximate hook in .github/workflows/main.yml could be:
```
- name: Publish package
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  uses: pypa/gh-action-pypi-publish@master
  with:
    user: __token__
    password: ${{ secrets.pypi_password }}
```

This assumes we have a github secret from pypi. We need 2 things for this automated step to work:

1. Need someone with authorization for the pypi package to set the github secret `pypi_password` [here](https://github.com/cloudevents/sdk-python/settings/secrets)
2. Need a PR adding the above job to workflows and merging it either into cloudevents/master or cloudevents/v1.0.0-dev
